const translations = {
  "it": {
    "navCvBtn": "About / CV",
    "heroTitle": "<span class=\"hero-line1\">Spazi Pubblici Relazionali</span><span class=\"hero-line2\">Architettura, Paesaggio, Dinamiche Sociali</span><span class=\"hero-line3\">Sostenibilità Ambientale, Sponge City</span>",
    "heroSubtitle": "Progettazione urbana e del paesaggio orientata alla rigenerazione ecologica,<br>alle infrastrutture resilienti e alla qualità dello spazio collettivo.",
    "aboutTitle": "Visione & Ricerca Progettuale",
    "aboutText": "\"Ciò che dà vita alla città, ciò che ne crea la dinamicità, sono i movimenti, i flussi, gli scambi relazionali ed economici che avvengono negli spazi pubblici collettivi e che conferiscono loro una funzione ulteriore: quella sociale.\"",
    "portfolioTitle": "Progetti Selezionati",
    "contactTitle": "Contatti & Collaborazioni:",
    "clickText": "Vedi Progetto →",
    "bioOfficesTitle": "Sedi Operative",
    "bioOfficesText": "Zürich | Savona | Roma",
    "bioFocusTitle": "Focus & Competenze",
    "bioFocusText": "<li>• Sponge City & Water Resilience</li><li>• Masterplanning & Spazi Pubblici</li><li>• Rigenerazione Ecologica Urbana</li><li>• Dettaglio Costruttivo Paesaggistico</li>",
    "bioExpTitle": "Esperienza",
    "bioExpText": "• Maurus Schifferli Landschaftsarchitek (Switzerland)<br>• Mecanoo (Olanda)<br>• Openfabric (Olanda/Italia)",
    "bioAboutTitle": "Profilo Professionale",
    "bioAboutText": "Architetto e Paesaggista specializzata nella progettazione di infrastrutture verdi, rigenerazione urbana e pianificazione del territorio resiliente. Con un'esperienza consolidata all'interno di studi d'architettura internazionali come Maurus Schifferli Landschaftsarchitek, Mecanoo e Openfabric. La mia ricerca si concentra sull'intersezione tra ecologia urbana, sostenibilità idrica (Sponge City) e dinamiche sociali dello spazio pubblico.",
    "bioPhilosophyTitle": "Approccio Progettuale",
    "bioPhilosophyText": "\"La progettazione del paesaggio contemporaneo non riguarda solo l'estetica, ma la capacità degli spazi pubblici di funzionare come sistemi ecologici attivi e catalizzatori di relazioni umane.\"",
    "cvDlText": "Scarica CV (PDF)"
  },
  "en": {
    "navCvBtn": "About / CV",
    "heroTitle": "<span class=\"hero-line1\">Relational Public Spaces</span><span class=\"hero-line2\">Architecture, Landscape, Social Dynamics</span><span class=\"hero-line3\">Environmental Sustainability, Sponge City</span>",
    "heroSubtitle": "Urban and landscape design focused on ecological regeneration,<br>resilient infrastructure, and the quality of collective space.",
    "aboutTitle": "Vision & Design Research",
    "aboutText": "\"What gives life to the city, what creates its dynamic nature, are movements, flows, relational and economic exchanges occurring in collective public spaces, giving them a further function: the social one.\"",
    "portfolioTitle": "Selected Projects",
    "contactTitle": "Inquiries & Collaborations:",
    "clickText": "View Project →",
    "bioOfficesTitle": "Offices",
    "bioOfficesText": "Zürich | Savona | Rome",
    "bioFocusTitle": "Focus & Skills",
    "bioFocusText": "<li>• Sponge City & Water Resilience</li><li>• Masterplanning & Public Spaces</li><li>• Urban Ecological Regeneration</li><li>• Landscape Detail Design</li>",
    "bioExpTitle": "Office Experience",
    "bioExpText": "• Maurus Schifferli Landschaftsarchitek (Switzerland)<br>• Mecanoo (Netherlands)<br>• Openfabric (Netherlands/Italy)",
    "bioAboutTitle": "Professional Profile",
    "bioAboutText": "Architect and Landscape Architect working at the intersection of landscape, urbanism, and ecology. Her practice focuses on the design of green infrastructure, urban regeneration, and resilient territories, exploring how landscape can respond to contemporary environmental and social challenges. With experience gained through collaborations with internationally recognised practices, including Maurus Schifferli Landschaftsarchitekten, Mecanoo, and Openfabric, her work investigates the relationship between urban ecology, water-sensitive design and Sponge City strategies, and the evolving social dynamics of public space.\nThrough an integrated and research-driven approach, she seeks to create resilient, adaptive, and meaningful landscapes that strengthen the relationship between people, water, and the living environment.",
    "bioPhilosophyTitle": "Design Approach",
    "bioPhilosophyText": "\"Contemporary landscape design is not just about aesthetics; it is about the ability of public spaces to function as active ecological systems and catalysts for human relationships.\"",
    "cvDlText": "Download CV (PDF)"
  },
  "de": {
    "navCvBtn": "Über / CV",
    "heroTitle": "<span class=\"hero-line1\">Relationale öffentliche Räume</span><span class=\"hero-line2\">Architektur, Landschaft, Soziale Dynamik</span><span class=\"hero-line3\">Umweltverträglichkeit, Schwammstadt</span>",
    "heroSubtitle": "Stadt- und Landschaftsplanung mit Fokus auf ökologische Regeneration,<br>resiliente Infrastrukturen und die Qualität kollektiver Freiräume.",
    "aboutTitle": "Ansatz & Entwurfsforschung",
    "aboutText": "\"Was der Stadt Leben verleiht und ihre Dynamik erzeugt, sind die Bewegungen, Ströme sowie der soziale und wirtschaftliche Austausch in kollektiven öffentlichen Räumen, die ihnen eine weitere Funktion verleihen: die soziale.\"",
    "portfolioTitle": "Ausgewählte Projekte",
    "contactTitle": "Kontakt & Zusammenarbeit:",
    "clickText": "Projekt Ansehen →",
    "bioOfficesTitle": "Standorte",
    "bioOfficesText": "Zürich | Savona | Rom",
    "bioFocusTitle": "Fokus & Kompetenzen",
    "bioFocusText": "<li>• Schwammstadt & Wasserresilienz</li><li>• Masterplanung & Öffentliche Räume</li><li>• Städtische Ökologische Regeneration</li><li>• Landschaftskonstruktionsdetails</li>",
    "bioExpTitle": "Büroerfahrung",
    "bioExpText": "• Maurus Schifferli Landschaftsarchitek (Switzerland)<br>• Mecanoo (Niederlande)<br>• Openfabric (Niederlande/Italien)",
    "bioAboutTitle": "Berufsprofil",
    "bioAboutText": "Architektin und Landschaftsarchitektin an der Schnittstelle von Landschaft, Städtebau und Ökologie. Ihr Schwerpunkt liegt auf der Gestaltung grüner Infrastrukturen, der urbanen Transformation und resilienter Landschaftsräume. Dabei untersucht sie, wie Landschaft auf die heutigen ökologischen und gesellschaftlichen Herausforderungen reagieren kann.\nDurch ihre Erfahrung in der Zusammenarbeit mit international renommierten Büros, darunter Maurus Schifferli Landschaftsarchitekten, Mecanoo und Openfabric, beschäftigt sie sich intensiv mit der Verbindung von urbaner Ökologie, wassersensibler Planung und Sponge-City-Strategien sowie mit den sich wandelnden sozialen Dynamiken des öffentlichen Raums.\nMit einem integrativen und forschungsorientierten Ansatz entwickelt sie resiliente, anpassungsfähige und identitätsstiftende Landschaften, die die Beziehung zwischen Mensch, Wasser und Lebensraum stärken.",
    "bioPhilosophyTitle": "Entwurfsansatz",
    "bioPhilosophyText": "\"Zeitgenössische Landschaftsplanung geht über Ästhetik hinaus; es geht um die Fähigkeit öffentlicher Räume, als aktive ökologische Systeme und Katalysatoren menschlicher Beziehungen zu wirken.\"",
    "cvDlText": "CV Herunterladen (PDF)"
  }
};